on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-18.0
    steps:
      - uses: duty-machine/duty-machine-action@master
        env:
          TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          EVENT: ${{ toJson(github.event) }}
